### PR TITLE
chore: release v0.5.2

### PR DESCRIPTION
**Pull request by techouse**
### Changes

---

Packages with breaking changes:

 - There are no breaking changes in this release.

### Packages with other changes:

 - [`envied` - `v0.5.2`](#envied---v052)
 - [`envied_generator` - `v0.5.2`](#enviedgenerator---v052)

---

#### `envied` - `v0.5.2`

 - **FEAT**: add ability to convert field name from camelCase to CONSTANT_CASE (#42)

#### `envied_generator` - `v0.5.2`

 - **FEAT**: add ability to convert field name from camelCase to CONSTANT_CASE (#42)
 - **FEAT**: generated files are now ignored in the coverage report (#62)
 - **FEAT**: add support for Uri fields (#70)
 - **FEAT**: add support for DateTime fields (#70)
 - **FEAT**: add support for obfuscated double fields (#72)
 - **FEAT**: add support for obfuscated num fields (#72)
 - **FEAT**: add support for enum fields (#73)

### CODE REVIEW

**Comment by techouse** [comment]
@petercinibulk I've drafted a release since people have been requesting these changes to be published 😇

**Comment by ThexXTURBOXx** [comment]
You forgot `feat: Obfuscated doubles and nums (#72)` :)

**Comment by techouse** [comment]
> You forgot `feat: Obfuscated doubles and nums (#72)` :)

Not sure how that escaped me. Thanx!

**Review by petercinibulk — APPROVED** [review]

**Comment by techouse** [comment]
@petercinibulk @ThexXTURBOXx  I've pushed the tag `v0.5.2` which made the release to pub.dev 🚀. Happy days 🍻

**Pull request merged**
