### PR TITLE
feat: add Enum support

### PR DESCRIPTION
**Pull request by techouse**
Addresses #26

Implements support for Enumerated types

- [x] unobfuscated  `Enum`, `Enum?`
- [x] obfuscated  `Enum`, `Enum?`
- [x] update example 

---

Generates

***.env***
```ini
enumValue=lorem
```

***example_enum.dart***
```dart
enum ExampleEnum { lorem, ipsum, dolor }
```

***env.dart***
```dart
import 'package:envied/envied.dart';

import 'example_enum.dart';

part 'env.g.dart';

@Envied(path: '.env')
final class Env {
  @EnviedField()
  static final ExampleEnum enumValue = _Env.enumValue;
}
```

***env.g.dart***
```dart
part of 'env.dart';

// coverage:ignore-file
// ignore_for_file: type=lint
final class _Env {
  static final ExampleEnum enumValue = ExampleEnum.values.byName('lorem');
}
```

---

**Caveat:** Any `Enum` will be checked for its values. If a non-existing value is used an `InvalidGenerationSourceError` will be thrown. The values are looked up using [`byName`](https://api.dart.dev/stable/3.1.5/dart-core/EnumByName/byName.html) which can throw an `ArgumentError` when a wrong value is supplied, however, this should be already caught by the generator.

### CODE REVIEW

**Comment by techouse** [comment]
@petercinibulk @ThexXTURBOXx once you have a minute, can you throw an eye on this? 😇

**Comment by techouse** [comment]
FYI @ryanaidilp in resolving the merge conflicts with #42 I reverted the examples that used `useConstantCase: true` to their previous state and I'll and an additional example file specifically using `useConstantCase: true`.

**Comment by ryanaidilp** [comment]
> FYI @ryanaidilp in resolving the merge conflicts with #42 I reverted the examples that used `useConstantCase: true` to their previous state and I'll and an additional example file specifically using `useConstantCase: true`.

No worries at all! If it helps streamline the process, feel free to revert the examples. Looking forward to the additional example file using `useConstantCase: true`. Thanks for the heads up! 😊

**Comment by techouse** [comment]
@petercinibulk please check once you have a minute :)

**Review by petercinibulk — APPROVED** [review]

**Pull request merged**
