### PR TITLE
refactor: Adding ability to convert field name from camelCase to CONSTANT_CASE if `varName` is not specified for `@EnvField`

### PR DESCRIPTION
**Pull request by ryanaidilp**
This pull request adds a new feature to the `envied` package, allowing the conversion of field names from camelCase to CONSTANT_CASE if the `@EnvField` annotation is not provided with a specific `varName`. The motivation behind this enhancement is to adhere to the Effective Dart rules of naming conventions, which specify that variables and field names should start with lowercase letters and use uppercase for the first letter of each subsequent word, such as `firstName`, `secondName`, and `getAllColors`.

With this new functionality, the `envied` package will automatically transform the field names into CONSTANT_CASE format when the `@EnvField` annotation is not explicitly assigned a `varName`. This conversion ensures compliance with the prescribed naming conventions, promoting consistency and readability in the codebase.

The implementation includes logic to detect when the `@EnvField` annotation is not provided with a `varName` and applies the necessary transformation to convert the field name from camelCase to CONSTANT_CASE. This feature adds flexibility and convenience to the package, enabling developers to adhere to the recommended naming conventions effortlessly.

This pull request aligns with the goals of the `envied` package by promoting best practices and making it easier for users to adopt effective coding standards. It contributes to the overall quality and maintainability of projects utilizing the `envied` package.

Thank you for considering this pull request. I am confident that this feature will enhance the functionality and usability of the `envied` package, benefiting developers who strive to follow the Effective Dart naming conventions.

### CODE REVIEW

**Comment by techouse** [comment]
Hi @ryanaidilp 

Can you please resolve the merge conflicts with the main branch?

**Comment by techouse** [comment]
Couple of observations:

1. this should not be a default behaviour but rather enabled by an annotation
2. you might also want to use somehting like [recase](https://pub.dev/packages/recase) instead of rolling your own string conversions

**Comment by ryanaidilp** [comment]
> Couple of observations:
> 
> 1. if this is a breaking change, it should not be a default behaviour but rather enabled by a flag
> 2. you might also want to use somehting like [recase](https://pub.dev/packages/recase) instead of rolling your own string conversions
> 
> ```dart
> import 'package:recase/recase.dart';
> 
> final String varName = 'camelCaseVariable'.constantCase; // becomes CAMEL_CASE_VARIABLE
> ```

Thank you for your feedback! I appreciate your suggestions.

Regarding your first point, I've implemented your advice and added a flag to enable and disable this feature. It's no longer the default behavior.

Additionally, I've integrated the `recase` package for more robust string conversions. Now, users can customize their string transformations easily.

I've already pushed these changes in my recent commit. Kindly review it, and feel free to let me know if you have any more suggestions or concerns. Your input is valuable to improve the package further.

**Comment by petercinibulk** [comment]
@ryanaidilp Sorry to make you have to handle conflicts again but we just pushed some updates that have conflicts with this PR

**Comment by ryanaidilp** [comment]
> @ryanaidilp Sorry to make you have to handle conflicts again but we just pushed some updates that have conflicts with this PR

No worries at all! I've resolved the conflicts in my recent commits. Let me know if there's anything else needed.

**Review by techouse — APPROVED** [review]

**Review by ryanaidilp — COMMENTED** [review]
LGTM 🚀

**Pull request merged**
