### PR TITLE
feat: optional path build.yaml option

### PR DESCRIPTION
**Pull request by techouse**
Supersedes #20 originally authored by @marcel-ploch

---

Adds option for supporting the following build.yaml

```yaml
targets:
  $default:
    builders:
      envied_generator|envied:
        options:
          path: .env.test
          override: true 
```

Only when **BOTH** `override` is `true` and the `path` is set will the generator resort to using the `path` provided in this build.yaml.

### CODE REVIEW

**Comment by techouse** [comment]
@marcel-ploch can you throw an eye on it

CC/ @petercinibulk @ThexXTURBOXx

**Review by marcel-ploch — APPROVED** [review]

**Comment by techouse** [comment]
I'll add some more explicit tests for this later in the evening.

**Comment by marcel-ploch** [comment]
I can help writing tests if you like. 
Just tell me what sort of testcases you have in mind ^^

**Comment by techouse** [comment]
I somehow managed to close this by mistake 🙈

Anyhow, this is ready for review

CC/ @marcel-ploch @petercinibulk @ThexXTURBOXx

**Review by marcel-ploch — APPROVED** [review]

**Review by petercinibulk — APPROVED** [review]

**Pull request merged**
