### PR TITLE
feat: Add obfuscation option

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
Since `envify` seems to have been abandoned and @techouse pointed me to this project, I will offer you my obfuscation option also here :)
For reference: https://github.com/frencojobs/envify/pull/28

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
I just noticed: We could also add the `obfuscate` option  to the `EnviedField` annotation to allow for individual field obfuscation.
Right now I am very stressed out. I will try to implement this as soon as I have done free time, though (Mabye also in an extra PR?)

**Comment by petercinibulk** [comment]
I love this! Obfuscation was something I was looking to add but hadn't had the time recently. Thanks! Can you add tests for these changes before I merge?

**Comment by petercinibulk** [comment]
I love this! Obfuscation was something I was looking to add but hadn't had the time recently. Thanks! Can you add tests for these changes before I merge?

Also I think we can merge this in and do a follow on PR for obfuscation per field

**Comment by ThexXTURBOXx** [comment]
Thank you very much for considering this! :)
Alas, I am currently not at home. I will try to finish the tests (and maybe even per-field obfuscation) until Monday, though!

**Comment by ThexXTURBOXx** [comment]
@petercinibulk I was able to fit this in today :)
Hope, everything is okay now! Per-field obfuscation is also already working!

**Review by petercinibulk — APPROVED** [review]

**Comment by petercinibulk** [comment]
@ThexXTURBOXx Thanks for getting that done! I went ahead and merged it in. I need to clean up the readme, so I will do my updates and add some information on using the obfuscation flag next week and then make a release.

**Comment by ThexXTURBOXx** [comment]
Hi, are there any updates on this? :)

**Comment by ThexXTURBOXx** [comment]
Thank you very much for the update!

**Pull request merged**
