### PR TITLE
feat: add Uri and DateTime support

### PR DESCRIPTION
**Pull request by techouse**
Addresses #23

Implements these new Dart types.

- [x] unobfuscated `Uri`, `Uri?`
- [x] unobfuscated `DateTime`, `DateTime?`
- [x] obfuscated `Uri`, `Uri?`
- [x] obfuscated `DateTime`, `DateTime?`
- [x] update example 

---

**Caveat:** Neither `Uri` nor `DateTime` have a `const` constructor, hence the variables can't be `const` but only `final`. This might hamper the use of `const` Env constructors and users should be aware of the limitation imposed by Dart itself.

### CODE REVIEW

**Comment by techouse** [comment]
@ThexXTURBOXx might need your input here to add obfuscation for `Uri` and `DateTime`

**Comment by ThexXTURBOXx** [comment]
I would suggest to treat `Uri` just the same way as a normal string. Just call it's factory in the end and you are done.
For `DateTime`, treat it like a normal `int` by converting it to `millisSinceEpoch`, obfuscating it then and convert it back to a `DateTime` afterwards.
However, make sure that the timezone is also properly converted and everything.

**Comment by techouse** [comment]
I think I could get away by just using a `String` (ISO8601) there too, since that's how I've implemented unobfuscated `DateTime`.

**Comment by ThexXTURBOXx** [comment]
In that case, that makes even more sense. Then you don't have to care about anything in that regard and should be fine!

**Comment by ThexXTURBOXx** [comment]
Also, thinking about it again, one could also probably obfuscate `double` values using their IEEE 754 representation. But, that would be a different issue and also require something like [this](https://pub.dev/packages/ieee754) in order to properly obtain the IEEE 754 representation.
Maybe, there is a small "hack" which one can use in order to bitwise-`xor` a `double` value with some other `double` or `int` something...

**Comment by techouse** [comment]
> Also, thinking about it again, one could also probably obfuscate `double` values using their IEEE 754 representation.

Would you mind making a PR with that feature?

**Comment by ThexXTURBOXx** [comment]
I need to think about that a bit first, so I will see when I have time for that :)

**Comment by techouse** [comment]
@ThexXTURBOXx @petercinibulk alrighty then this PR is ready for review :)

**Comment by techouse** [comment]
@petercinibulk please approve & merge this once you can so that we can progress with #72

**Review by ThexXTURBOXx — APPROVED** [review]
I should also express my approval for this PR

**Review by petercinibulk — APPROVED** [review]
Awesome work!

**Pull request merged**
